import Link from 'next/link';
import { notFound,redirect } from 'next/navigation';
import { api,DashboardApiError } from '../../../lib/api';
import { can,getDashboardAccess } from '../../../lib/permissions';
import { issuePunishmentAction,reopenTicketAction,reversePunishmentAction,updateTicketStatusAction } from '../actions';
import ActionButton from '../../../components/ActionButton';
import LiveRefresh from '../../../components/LiveRefresh';
import styles from '../tickets.module.css';

type Message={id:number;discord_message_id:string;discord_user_id:string;author_name:string|null;content:string;attachments:Array<{name?:string;url?:string}>;is_bot:boolean;discord_created_at:string};
type Event={id:number;event_type:string;actor_user_id:string|null;actor_name:string|null;details:any;created_at:string};
type Punishment={id:number;public_id:string;target_user_id:string;target_name:string|null;action_type:string;duration_seconds:number|null;reason:string;internal_notes:string;status:string;issued_by_name:string|null;issued_by_user_id:string;issued_at:string|null;expires_at:string|null;reversed_by_name:string|null;reversal_reason:string|null;reversed_at:string|null;failure_reason:string|null;created_at:string};
type Ticket={id:number;public_id:string;type_key:string;type_label:string;type_emoji:string|null;allow_punishments:boolean;guild_id:string;channel_id:string|null;opener_user_id:string;opener_name:string|null;subject:string;description:string;involved_user_id:string|null;evidence_links:string;status:string;priority:string;claimed_by_name:string|null;claimed_at:string|null;close_reason:string|null;closed_by_name:string|null;closed_at:string|null;transcript_message_id:string|null;created_at:string;updated_at:string;messages:Message[];events:Event[];punishments:Punishment[]};
function pretty(value:string){return value.replaceAll('_',' ')}
function duration(seconds:number|null){if(!seconds)return 'Permanent / no set duration';if(seconds%86400===0)return `${seconds/86400} day${seconds===86400?'':'s'}`;if(seconds%3600===0)return `${seconds/3600} hour${seconds===3600?'':'s'}`;return `${Math.round(seconds/60)} minutes`;}

export default async function TicketDetailPage({params}:{params:Promise<{id:string}>}){
  const access=await getDashboardAccess();if(!can(access,'tickets.view'))redirect('/');
  const {id}=await params;if(!/^\d+$/.test(id))notFound();
  let ticket:Ticket;try{ticket=await api<Ticket>(`/api/tickets/${id}`);}catch(error){if(error instanceof DashboardApiError&&error.status===404)notFound();throw error;}
  const discordUrl=ticket.channel_id?`https://discord.com/channels/${ticket.guild_id}/${ticket.channel_id}`:null;
  const canTranscript=can(access,'tickets.transcripts');
  return <>
    <LiveRefresh interval={20000}/>
    <div className="detailBreadcrumb"><Link href="/tickets">← Tickets</Link></div>
    <header className="pageHeader"><div><p className="eyebrow">{ticket.public_id} · {ticket.type_emoji} {ticket.type_label}</p><h1>{ticket.subject}</h1><p>Opened by {ticket.opener_name||ticket.opener_user_id} · {new Date(ticket.created_at).toLocaleString()}</p></div><div className="headerActions">{discordUrl?<a className="button primary" href={discordUrl} target="_blank" rel="noreferrer">Open Discord ticket ↗</a>:null}<span className={`${styles.status} ${styles[ticket.status as keyof typeof styles]||''}`}>{pretty(ticket.status)}</span></div></header>
    <div className={styles.detailGrid}><div>
      <section className={styles.section}><h2>Initial request</h2><p>{ticket.description}</p>{ticket.evidence_links?<><h2>Initial evidence / links</h2><p>{ticket.evidence_links}</p></>:null}</section>
      {canTranscript?<section className={styles.section}><h2>Ticket conversation</h2>{ticket.messages?.length?ticket.messages.map(message=><div className={styles.message} key={message.id}><div className={styles.messageTop}><strong>{message.author_name||message.discord_user_id}{message.is_bot?' · BOT':''}</strong><span>{new Date(message.discord_created_at).toLocaleString()}</span></div>{message.content?<p>{message.content}</p>:null}{message.attachments?.map((file,index)=>file.url?<a href={file.url} target="_blank" rel="noreferrer" key={`${message.id}-${index}`}>{file.name||'Attachment'} ↗</a>:null)}</div>):<div className={styles.empty}>No conversation messages were captured.</div>}</section>:<section className={styles.section}><h2>Ticket conversation</h2><p>You need the View transcripts permission to read preserved ticket messages.</p></section>}
      <section className={styles.section}><h2>Punishment history</h2>{ticket.punishments?.length?ticket.punishments.map(p=><div className={styles.punishment} key={p.id}><div className={styles.punishmentHeader}><strong>{p.public_id} · {pretty(p.action_type)}</strong><span className={`${styles.status} ${styles[p.status as keyof typeof styles]||''}`}>{p.status}</span></div><p><strong>Member:</strong> {p.target_name||p.target_user_id}<br/><strong>Duration:</strong> {duration(p.duration_seconds)}<br/><strong>Reason:</strong> {p.reason}<br/><strong>Issued by:</strong> {p.issued_by_name||p.issued_by_user_id}</p>{p.failure_reason?<p><strong>Discord error:</strong> {p.failure_reason}</p>:null}{p.reversal_reason?<p><strong>Reversed by:</strong> {p.reversed_by_name||'Staff'}<br/><strong>Reversal reason:</strong> {p.reversal_reason}</p>:null}{can(access,'moderation.reverse')&&['active','completed'].includes(p.status)?<form className={styles.dangerForm} action={reversePunishmentAction.bind(null,id,String(p.id))}><label className="field"><span>Required reversal reason</span><textarea className="textarea" name="reversal_reason" required rows={2}/></label><ActionButton label={`Reverse ${p.public_id}`} variant="danger" confirmMessage={`Reverse ${p.public_id}? Discord will undo the active action when possible and permanently record this reversal.`}/></form>:null}</div>):<div className={styles.empty}>No punishments are linked to this ticket.</div>}</section>
      <section className={styles.section}><h2>Case timeline</h2>{ticket.events?.map(event=><div className={styles.event} key={event.id}><span>{new Date(event.created_at).toLocaleString()}</span><strong>{pretty(event.event_type)}</strong><span>{event.actor_name||event.actor_user_id||'Saucin AI'}</span></div>)}</section>
    </div><aside>
      <section className={styles.section}><h2>Ticket details</h2><div className={styles.facts}><div><span>Status</span><strong>{pretty(ticket.status)}</strong></div><div><span>Priority</span><strong>{ticket.priority}</strong></div><div><span>Opened by</span><strong>{ticket.opener_name||ticket.opener_user_id}</strong></div><div><span>Involved member</span><strong>{ticket.involved_user_id||'Not provided'}</strong></div><div><span>Claimed by</span><strong>{ticket.claimed_by_name||'Unclaimed'}</strong></div><div><span>Last updated</span><strong>{new Date(ticket.updated_at).toLocaleString()}</strong></div></div></section>
      {can(access,'tickets.manage')&&ticket.status!=='closed'?<section className={styles.section}><h2>Staff workflow</h2><form action={updateTicketStatusAction.bind(null,id,'claimed')}><label className="field"><span>Optional note</span><input className="input" name="note"/></label><div className="headerActions"><ActionButton label="Mark claimed" variant="primary"/><ActionButton label="Waiting on user" formAction={updateTicketStatusAction.bind(null,id,'awaiting_user')}/><ActionButton label="Release to queue" formAction={updateTicketStatusAction.bind(null,id,'open')}/></div></form><p>Releasing clears the current assignment and returns the ticket to the open staff queue. Close the ticket from Discord when the case is complete.</p></section>:null}
      {can(access,'moderation.punish')&&ticket.allow_punishments&&ticket.status!=='closed'?<section className={styles.section}><h2>Issue Discord punishment</h2><form action={issuePunishmentAction.bind(null,id)}><div className={styles.actionGrid}><label className={`field ${styles.full}`}><span>Discord user ID</span><input className="input" name="target_user_id" required defaultValue={ticket.involved_user_id||''}/></label><label className="field"><span>Action</span><select className="input select" name="action" required><option value="warning">Warning</option><option value="timeout">Timeout</option><option value="kick">Kick</option><option value="temporary_ban">Temporary ban</option><option value="permanent_ban">Permanent ban</option></select></label><label className="field"><span>Duration</span><select className="input select" name="duration_seconds" defaultValue=""><option value="">No duration</option><option value="600">10 minutes</option><option value="3600">1 hour</option><option value="86400">1 day</option><option value="604800">7 days</option><option value="2592000">30 days</option></select></label><label className={`field ${styles.full}`}><span>Rule and user-facing reason</span><textarea className="textarea" name="reason" required rows={4}/></label><label className={`field ${styles.full}`}><span>Internal staff notes</span><textarea className="textarea" name="internal_notes" rows={3}/></label></div><p>Submitting applies the Discord action immediately. Confirm the member, action, duration, and reason first.</p><ActionButton label="Apply punishment" pendingLabel="Applying punishment…" variant="primary" confirmMessage="Apply this Discord punishment now? The action will be executed immediately and saved permanently in the audit history."/></form></section>:null}
      {ticket.status==='closed'?<section className={styles.section}><h2>Closure</h2><p><strong>{ticket.close_reason||'Ticket closed.'}</strong><br/>{ticket.closed_by_name?`Closed by ${ticket.closed_by_name}`:''}<br/>{ticket.closed_at?new Date(ticket.closed_at).toLocaleString():''}</p>{can(access,'tickets.manage')?<form action={reopenTicketAction.bind(null,id)}><ActionButton label="Reopen ticket" pendingLabel="Reopening…" variant="primary" confirmMessage={`Reopen ${ticket.public_id}? Saucin AI will create a new private Discord channel and continue this same case.`}/></form>:null}</section>:null}
    </aside></div>
  </>;
}
