import Link from 'next/link';
import { redirect } from 'next/navigation';
import { api } from '../../../../lib/api';
import { can, getDashboardAccess } from '../../../../lib/permissions';
import styles from '../../moderation.module.css';

type Row={id:number;public_id:string;rule_title:string;confidence:number|string;status:string;created_at:string;message_content:string;recommended_action:string;delete_message_recommended:boolean;offense_number:number};
type Data={user_id:string;summary:{total:number;pending:number;confirmed:number;dismissed:number;last_known_name:string|null};cases:Row[]};
function when(v:string){return new Date(v).toLocaleString()}
export default async function ModerationUserPage({params}:{params:Promise<{userId:string}>}){const access=await getDashboardAccess();if(!can(access,'moderation.view'))redirect('/');const {userId}=await params;const data=await api<Data>(`/api/moderation/users/${encodeURIComponent(userId)}`);return <><div className="detailBreadcrumb"><Link href="/moderation">← Moderation</Link></div><header className="pageHeader compactPageHeader"><div><p className="eyebrow">MEMBER HISTORY</p><h1>{data.summary.last_known_name||data.user_id}</h1><p>Discord ID {data.user_id} · moderation observations and staff review history.</p></div></header><div className={styles.stats}><div className={styles.stat}><span>Total cases</span><strong>{data.summary.total||0}</strong></div><div className={styles.stat}><span>Pending</span><strong>{data.summary.pending||0}</strong></div><div className={styles.stat}><span>Confirmed</span><strong>{data.summary.confirmed||0}</strong></div><div className={styles.stat}><span>Dismissed</span><strong>{data.summary.dismissed||0}</strong></div></div><section className="panel"><div className="panelTitle"><div><h2>Case history</h2><p>Dismissed cases stay visible so staff can evaluate false positives and patterns.</p></div></div>{data.cases.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Case</th><th>Rule</th><th>Message</th><th>Status</th><th>Date</th></tr></thead><tbody>{data.cases.map(c=><tr key={c.id}><td><Link href={`/moderation/${c.id}`}>{c.public_id}</Link></td><td><strong>{c.rule_title}</strong><small className={styles.ruleEscalation}>Offense #{c.offense_number||1} · {c.recommended_action.replaceAll('_',' ')}{c.delete_message_recommended?' + delete message':''}</small></td><td><Link className={styles.caseLink} href={`/moderation/${c.id}`}><small>{c.message_content}</small></Link></td><td><span className={`${styles.badge} ${styles[c.status as 'pending']||''}`}>{c.status}</span></td><td>{when(c.created_at)}</td></tr>)}</tbody></table></div>:<div className={styles.empty}>No moderation history.</div>}</section></>}
